name = "DeckCraft"
author = "UltraStorm"
version = "1.0.0+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfe6852de700bb2913e0358037e1f1874302cc82935ffd6f1597773bc1eb0f3d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
